### ISSUE TITLE
executor_service

### ISSUE THREAD

**Issue by chrisz2zz** [smallnest/concurrency-programming-via-rust#12]
42页

支持闭包、Future 等任务形式:
`pool.spawn(async {});`

spawn方法应该没有

43页
4. 提供方便的线程池构建器
ThreadPoolExecutor应该没有 像是把threadpool_executor库的写错到这里了

**Comment by smallnest** [comment]
你看看对应的代码库中的代码。相关代码应该是都编译通过的。
