### ISSUE TITLE
ch01 Thread.pdf error

### ISSUE THREAD

**Issue by peanut-cc** [smallnest/concurrency-programming-via-rust#5]
![image](https://user-images.githubusercontent.com/55480838/200271924-dd41569c-0096-4739-8f88-be3c59754c56.png)

应该是 “认为” ？

**Comment by chrisz2zz** [comment]
"实际上也有人**任务**纤程也属于协程，**因为因为**这两个并没有一个严格的定义"  => "实际上也有人认为纤程也属于协程，因为这两个并没有一个严格的定义"

**Comment by smallnest** [comment]
fixed
