### ISSUE TITLE
error: no matching package named `atomic_mpmc` found

### ISSUE THREAD

**Issue by longguzzz** [smallnest/concurrency-programming-via-rust#7]
error: the crate `atomic_mpmc` could not be found in registry index

**Comment by smallnest** [comment]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/865763/229430696-7081860d-37ab-4597-9013-3a84a7700eaa.png">

**Comment by longguzzz** [comment]
不知道为什么没法自动找到。不过，最后通过atomic_mpmc = {git = "https://github.com/DexterHaxxor/atomic_mpmc.git" } 
解决了。

**Comment by miaomiao1992** [comment]
作者删库跑路了

**Comment by smallnest** [comment]
嗯嗯，我会在代码中删除它
